name: Hello World

on: push

jobs:
  stage-1:
    name: Stage 1 - Hello
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, world!"

  stage-2:
    name: Stage 2 - Middle
    runs-on: ubuntu-latest
    needs: stage-1
    steps:
      - name: Do something in stage 2
        run: echo "This is stage 2"

  stage-3:
    name: Stage 3 - Goodbye
    runs-on: ubuntu-latest
    needs: stage-2
    steps:
      - name: Say Goodbye
        run: echo "Goodbye, world!"
