name: CI/CD Pipeline

on:
  push:
  workflow_dispatch:  # Allows manual re-run if needed

jobs:
  build:
    name: Stage 1 - Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build
        run: echo "Building the application..."

  test:
    name: Stage 2 - Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Tests
        run: echo "Running tests..."

 
